apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: captainhook-pdb
  labels:
    app.kubernetes.io/name: captainhook
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: captainhook
