spring:
  application:
    name: proxy
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    env:
      access: read_only
    health:
      probes:
        enabled: true

logging:
  level:
    org:
      springframework:
        web:
          service: TRACE
      titan:
        proxy: DEBUG

