spring:
  application:
    name: proxy
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    env:
      access: read_only
    health:
      probes:
        enabled: true

captain-hook:
  jenkins:
    apim:
      url: http://dev-jenkins.dev-jenkins.svc.cluster.local:8080
    core-engineering:
      url: http://jenkins.sandbox-ci.svc.cluster.local:8080

logging:
  level:
    org:
      springframework:
        web:
          service: INFO
      titan:
        proxy: INFO

