spring:
  application:
    name: proxy
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    env:
      enabled: true
    health:
      probes:
        enabled: true

logging:
  level:
    org:
      apache:
        hc:
          client5:
            http: DEBUG
