apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: captainhook
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 595468393306.dkr.ecr.eu-west-1.amazonaws.com/captainhook
configMapGenerator:
  - name: captainhook-configmap
    files:
      - application.properties
secretGenerator:
  - name: captainhook-secret
    envs:
      - secrets.properties
     

